### ISSUE TITLE
showing java instead of bedrock 

### ISSUE THREAD

**Issue by el211** [rtm516/FloodgatePlaceholders#15]
![image](https://user-images.githubusercontent.com/86126606/212741386-47df10d8-5214-40b6-9397-8613dd39b195.png)
here is an screenshot uploaded on bedrock , it shows Java

**Comment by rtm516** [comment]
This is due to your floodgate setup being wrong, this plugin only pulls the data from the floodgate API. Please head over to the #support channel in the GeyserMC discord @ https://discord.gg/geysermc
