### ISSUE TITLE
Add %floodgate_isbedrock% placeholder and return boolean uncolored value

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [rtm516/FloodgatePlaceholders#16]
Hello,
so it becomes impossible to use changeoutput papi expansion because we cannot try ifmatch:&8[&aJava&8] because this will never match you can test it yourself, there is no way to try to target this output because %floodgate_device% is always colored, and papi never apply colors

this boolean value would be either `true` or `false` without any coloring, which can help us utilize changeoutput papi expansion

**Comment by rtm516** [comment]
You can change the config to change how device is shown

**Comment by MotikaCraft-TheJoshua** [comment]
ok thank you
but is there a way to purely get true/false answer like is it bedrock client or not? not to get specific device or else(?)

**Comment by MotikaCraft-TheJoshua** [comment]
It would be greatly useful to have 1 placeholder for determination between 2 major MC versions with simple boolean value
I'm actually surprised there is no such placeholder
Also, i could PR for this if you'd like

**Comment by rtm516** [comment]
Your welcome to PR it, I wont get chance until after the holidays

**Comment by MotikaCraft-TheJoshua** [comment]
> Your welcome to PR it, I wont get chance until after the holidays

Done at https://github.com/rtm516/FloodgatePlaceholders/pull/17

Thank you in advance regardless if it gets approved or not, i just think (and i need) this placeholder would be very useful, besides device and other ones.

**Comment by rtm516** [comment]
Merged PR and released as v1.5.0
