### ISSUE TITLE
Проблема с чтением

### ISSUE THREAD

**Issue by snglvm** [rtm516/FloodgatePlaceholders#18]
Доброго времени суток. Загрузил плагин на сервер, ядро Purpur (1.20 fork PaperMC). Не читает плагин. Может быть есть зависимые плагины без которых данный плагин не может работать? Подскажите, пожалуйста..

![2024-01-18_20-35-37](https://github.com/rtm516/FloodgatePlaceholders/assets/117341512/32b72ed5-caef-41c1-83ff-f1b3194dba3c)

**Comment by rtm516** [comment]
It's an extension to Placeholder API. Please follow the download instructions in the readme to install it correctly.
