### ISSUE TITLE
%floodgate_isbedrock% dosent't work with global linking

### ISSUE THREAD

**Issue by Funasitien** [rtm516/FloodgatePlaceholders#19]
If you are linked to a Minecraft Java account, %floodgate_isbedrock% == false =! true.
As I use this placeholder for texture pack, it's quite problematic

Other possible solution than editing %floodgate_isbedrock% : Make a new placeholder %floodgate_islinked%

**Comment by rtm516** [comment]
It should work, are you running this on a backend server behind a proxy? If so make sure you have your proxy setup configured properly to support passing floodgate data down. There is info in the floodgate setup guide on how to do this.
