### ISSUE TITLE
[feature] papi ecloud

### ISSUE THREAD

**Issue by TOWUK** [rtm516/FloodgatePlaceholders#3]
can be made easier and created **expansion** for PAPI ecloud? to avoid uploading as an additional plugin...
(https://api.extendedclip.com/all/)
![image](https://user-images.githubusercontent.com/28830162/92301640-f2ab2e80-ef6d-11ea-99d7-4441dead26ce.png)

**Comment by rtm516** [comment]
I have added this to eCloud and also updated to Floodgate 2.0.
https://api.extendedclip.com/expansions/floodgate/
