### ISSUE TITLE
[FEATURE REQUEST] None Message Placeholders

### ISSUE THREAD

**Issue by Romvnly-Gaming** [rtm516/FloodgatePlaceholders#9]
Allow the none message to use placeholders aswell. This would be amazing for showing bedrock players their true Xbox username and showing Java theirs. 

Here is what I'm trying to do:
    xbox-username:
      none: '%player_name%'
      found: '%username%'
      
 Result on Java:
 
![javaw_mvshfnK3RU](https://user-images.githubusercontent.com/62443489/115497888-80f0ce00-a23a-11eb-844a-ef1c1830de6c.png)

Expected Behavior: 
It allows placeholders in the none message.

**Comment by Romvnly-Gaming** [comment]
My disappoint that this issue is 8 months old is immeasurable and my day is ruined.

**Comment by zOIDAdaJulian** [comment]
Have the same Problem on Paper 1.18 at the moment! ;D
When Floodgate Expansion is enabled, nearly all other placeholders fail ^^
